name: Deploy

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{secrets.KEY}}" > "$HOME/.ssh"
      - run: chmod 600 "$HOME/.ssh/KEY"

      - run: npm ci
      - run: npm run build

      - run: rsync -e "ssh -p 20022 -i $HOME/.ssh/KEY -o StrictHostKeyChecking=no" --archive --compress --delete . 159.203.176.10
